server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api   #路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    user-service: /user/** # 用户微服务(zuul自定义配置路由,可直接通过/user访问user-service服务）
    food-service: /food/** # 食物微服务
    dairy-service: /dairy/**
  retryable: true  #开启重试
      #跨域不能显示cookie方法
  add-host-header: true      #允许携带域名信息
  sensitive-headers: false   #覆盖默认敏感头信息
ribbon:
  connectionTimeout: 5000 #获取连接超时时间
  readTimeout: 5000 #通讯超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
health:
  jwt:
    publicKeyPath: F:\graduationproject\health-manage-parent\tmp\rsa\rsa.pub
spring:
  application:
    name: health-gateway
