server:
  port: 8002
spring:
  application:
    name: sms-service
  rabbitmq:
    host: localhost
    username: health
    password: health
    virtual-host: /health
health:
  sms:
    accessKeyId: ************************
    accessKeySecret: ******************************
    signName: 雨霖铃  #签名名称
    verifyCodeTemplate: SMS_176523981 #模板名称